In [1]:
from torch.nn import Softmax
import torch
import numpy  as np

Давайте теперь посмотрим, как работает более общий вариант self-attention - когда в качестве ключей, запросов и значений используются разные матрицы.

На вход мы получаем всё ту же матрицу

Input =  \begin{matrix} 1 & 0 \\ 0 & 1 \\ 1 & 1 \\ 0 & 0\end{matrix} 

Общий алгоритм состоит из следующих основных шагов:

1. Найти значения ключей, запросов и значений, используя линейное преобразование

    Keys =Input⋅Proj_k + Bias_K

    Queries = Input * Proj_Q + Bias_Q

    Values = Input * Proj_V + Bias_V

2. Найти матрицу попарного сходства, используя полученные матричное произведение запросов и ключей 

    Logits=Queries * Keys.T
 
3. Найти коэффициенты усреднения, нормировав матрицу попарного сходства с помощью softmax по строкам 
    AttScores = softmax(Logits, rows)

4. Найти результат с помощью матричного произведения матриц значений и коэффициентов 
Result=AttScores * ValuesResult


Вам требуется найти значение матрицы Result с учётом следующих параметров преобразования:

Proj_K = \begin{matrix}(1 & 0 \\ 0 & 0)\end{matrix} 

Proj_Q = \begin{matrix}(0 & 0 \\ 1 & 0)\end{matrix}

Proj_V = \begin{matrix}(1 & 0 \\ 0 & 1)\end{matrix}

Bias_K = Bias_Q = Bias_V = \begin{matrix}(0 & 0)\end{matrix}


Результат запишите в виде матрицы, на одной строке - элементы одной строки матрицы, разделённые пробелами. В качестве десятичного разделителя используйте точку. Ответ округлите до не менее чем двух знаков после запятой.

## 1

In [2]:
Input = np.array([[1, 0], [0, 1], [1, 1], [0, 0]]) 


Proj_K = np.array([[1, 0], [0, 0]]) 
Proj_Q = np.array([[0, 0], [1, 0]]) 
Proj_V = np.array([[1, 0], [0, 1]]) 

keys = Input @ Proj_K
queries = Input @ Proj_Q
values  = Input @ Proj_V

## 2

In [3]:
logits = queries @ keys.T
logits

array([[0, 0, 0, 0],
       [1, 0, 1, 0],
       [1, 0, 1, 0],
       [0, 0, 0, 0]])

## 3

In [27]:
sm = Softmax(dim=1)
AttScores = sm(torch.tensor(logits).float())
AttScores 

tensor([[0.2500, 0.2500, 0.2500, 0.2500],
        [0.3655, 0.1345, 0.3655, 0.1345],
        [0.3655, 0.1345, 0.3655, 0.1345],
        [0.2500, 0.2500, 0.2500, 0.2500]])

## 4

In [28]:
result = AttScores @ torch.tensor(values).float()
result

tensor([[0.5000, 0.5000],
        [0.7311, 0.5000],
        [0.7311, 0.5000],
        [0.5000, 0.5000]])

In [29]:
np.round(np.array(result), 3)

array([[0.5  , 0.5  ],
       [0.731, 0.5  ],
       [0.731, 0.5  ],
       [0.5  , 0.5  ]], dtype=float32)

In [31]:
# 0.5   0.5
# 0.731 0.5
# 0.731 0.5
# 0.5   0.5